### ISSUE TITLE
Duplication of remix, original mix...

### ISSUE THREAD

**Issue by 0OOOOOOO0** [Sorrow446/Qo-DL#63]
Can you fix this bug please?

**Comment by DashLt** [comment]
What? Please elaborate.

**Comment by 0OOOOOOO0** [comment]
The original mix, remix... is duplicated in the tags and in the file name.

Example:
01. Title (Artist Remix) (Artist Remix)
02. Title (Original Mix) (Original Mix)

**Comment by 0OOOOOOO0** [comment]
Try this album and you'll see what I mean.

`https://www.qobuz.com/gb-en/album/bitching-bob-julia-remixes-hertz-david-moleon/wjxz4tiwcwmta`

**Comment by DashLt** [comment]
Identified the issue, fix will come shortly. (version was being added in parenthesis, will make sure not to do that if it's in the title already)

**Comment by DashLt** [comment]
This has been fixed in f6d86b4, and will be compiled for 5d.

**Comment by 0OOOOOOO0** [comment]
Thank you very much for updating, but I'm sorry to tell you that it still doesn't work, as much if I put Y as if I put N in "versionInTitle =".

> python Qo-DL.py -u https://www.qobuz.com/gb-en/album/bitching-bob-julia-remixes-hertz-david-moleon/wjxz4tiwcwmta
> The API did not return a(n) Composer. Tag will be left empty.
> Downloading track 1 of 2: Bitching Bob (David Moleon Remix) - 320kbps MP3
> [*] 12.0 MB / 12.0 MB @ 8.6 MB/s [##################] [100%, 0s left]
> Traceback (most recent call last):
>   File "Qo-DL.py", line 719, in <module>
>     init()
>   File "Qo-DL.py", line 701, in init
>     rip(album_id, isTrack, session, comment, formatId, alcovs, downloadDir, fp,
> keepCover)
>   File "Qo-DL.py", line 299, in rip
>     add_mp3_tags(temporary_filename, metadata)
>   File "Qo-DL.py", line 127, in add_mp3_tags
>     id3tag = legend[tag]
> KeyError: 'VERSION'
>

**Comment by DashLt** [comment]
oops, fixed it, sorry!

**Comment by 0OOOOOOO0** [comment]
1.000.000... of Thank you @DashLt, @Sorrow446 and @TitouanGendron for everything you do for us. ;)

**Comment by botezat** [comment]
**DashLt** sorry, not working...
![1](https://user-images.githubusercontent.com/50467655/61666102-57121c80-acdf-11e9-86ec-b3b4c064736b.jpg)
