### ISSUE TITLE
Multiple albums

### ISSUE THREAD

**Issue by 0OOOOOOO0** [Sorrow446/Qo-DL#70]
It doesn't allow me to download more than one album, i use the command "python Qo-DL.py -list Albums.txt"

> Traceback (most recent call last):
  File "C:\Program Files\Qo-DL\Qo-DL.py", line 711, in <module>
    init()
  File "C:\Program Files\Qo-DL\Qo-DL.py", line 693, in init
    rip(album_id, isTrack, session, comment, formatId, alcovs, downloadDir, fp,
keepCover)
  File "C:\Program Files\Qo-DL\Qo-DL.py", line 211, in rip
    and ver not in metadata["TITLE"] \
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by DashLt** [comment]
That last error is the result of a different bug which I just fixed, please test.

**Comment by 0OOOOOOO0** [comment]
This time it doesn't give me error but it still doesn't allow me multiple downloads, it only downloads one album, it turns out that the one that downloads me is the last not the first two.

**Comment by 0OOOOOOO0** [comment]
Put the "bug" label please.

**Comment by jimsaye** [comment]
> This time it doesn't give me error but it still doesn't allow me multiple downloads, it only downloads one album, it turns out that the one that downloads me is the last not the first two.

i have the same bug just the last of the list is download

**Comment by 0OOOOOOO0** [comment]
You've made me very happy @DashLt for getting multiple downloads, thank you so much.  :)
